CREATE TABLE IF NOT EXISTS APPLICATION_USERS
(
    ID       SERIAL PRIMARY KEY,
    LOGIN    VARCHAR(512) NOT NULL CHECK ( LENGTH(LOGIN) > 0 ) UNIQUE,
    PASSWORD VARCHAR(512) NOT NULL CHECK ( LENGTH(PASSWORD) > 0 )
);
