SELECT PRODUCT.ID,
       PRODUCT.NAME,
       COORDINATES.X,
       COORDINATES.Y,
       PRODUCT.CREATION_DATE,
       PRODUCT.PRICE,
       PRODUCT.UNIT_OF_MEASURE_ID,
       PRODUCT.CREATOR_ID,
       ORGANIZATION.ID   AS O_ID,
       ORGANIZATION.NAME AS O_NAME,
       ORGANIZATION.ANNUAL_TURNOVER,
       ORGANIZATION.ORGANIZATION_TYPE_ID,
       ADDRESS.STREET,
       ADDRESS.ZIP_CODE
FROM PRODUCT
         JOIN COORDINATES ON COORDINATES.ID = PRODUCT.COORDINATES_ID
         JOIN ORGANIZATION ON ORGANIZATION.ID = PRODUCT.MANUFACTURER
         JOIN ADDRESS ON ADDRESS.ID = ORGANIZATION.ADDRESS_ID;
