-- CREATE NEW USER
INSERT INTO APPLICATION_USERS (LOGIN, PASSWORD)
VALUES (?, ?);

-- GET USER ID BY LOGIN
SELECT ID
FROM APPLICATION_USERS
WHERE LOGIN = ?;

-- GET USER LOGIN BY ID
SELECT LOGIN
FROM APPLICATION_USERS
WHERE ID = ?;

-- 0 IF LOGIN IS NOT IN DATABASE OTHERWISE 1
SELECT COUNT(LOGIN)
FROM APPLICATION_USERS
WHERE LOGIN = ?;

-- GET ID OF THE USER USING LOGIN AND PASSWORD
SELECT ID
FROM APPLICATION_USERS
WHERE LOGIN = ?
  AND PASSWORD = ?;
